### ISSUE TITLE
Brush not working in LineChart after upgrade to D3 v6

### ISSUE THREAD

**Issue by ewaldman** [dc-js/dc.js#1772]
Hi.
I am using DC version 4.2.0. I upgraded my D3 to 6.2.0 and now the brush on my LineChart does not work.
When dragging the brush it does indeed filter out the other charts, however when releasing the brush it snaps back and nothing is filtered out. Also, after releasing the brush, the chart continuously redraws itself. When I moved back to D3 version 5.16.0 it works like a charm.

**Comment by gordonwoodhull** [comment]
Hi @ewaldman, thanks for the report!

Brushing works okay in [the main page](http://dc-js.github.io/dc.js/) as well as [this example](http://dc-js.github.io/dc.js/examples/brush-ordinal.html).

Are you using any custom event handlers in your application? D3 changed the signature for event handlers so that the event is passed as the first argument instead of using a global, so pretty much all event handlers need to be changed.

**Comment by ewaldman** [comment]
Thank you for responding. 
Once I added the 'event' parameter to events the brushes do indeed work.

However, I have another question.

The event I am using is renderlet.
The old code was:
this.timeLineChart.on('renderlet', ( chart) => {
          chart.select('svg').attr('width', null).attr('height', null).attr('viewBox',
            '0 0 ' + TIME_LINE_WIDTH + ' ' + 300).attr('preserveAspectRatio', 'xMinYMin'); 
        });

Based on your answer above I added event , and this is the new function:

this.timeLineChart.on('renderlet', (event, chart) => {
          chart.select('svg').attr('width', null).attr('height', null).attr('viewBox',
            '0 0 ' + TIME_LINE_WIDTH + ' ' + 300).attr('preserveAspectRatio', 'xMinYMin');
        });

However, google chrome is giving errors.  

Uncaught TypeError: Cannot read property 'select' of undefined
    at LineChart.<anonymous> (myService.js:1887)
    at Dispatch.call (dispatch.js:57)
    at SVGSVGElement.<anonymous> (dc.js:1979)
    at Dispatch.call (dispatch.js:57)
    at tick (schedule.js:141)
    at timerFlush (timer.js:61)
    at wake (timer.js:71)

Any tips ?

Thank you.

**Comment by ewaldman** [comment]
On further investigation , it seems that my first way of the function was right.


this.timeLineChart.on('renderlet', ( chart) => {
chart.select('svg').attr('width', null).attr('height', null).attr('viewBox',
'0 0 ' + TIME_LINE_WIDTH + ' ' + 300).attr('preserveAspectRatio', 'xMinYMin');
});

'renderlet' is the event name, and the listener function is the second param. However, doing it that way, the brushes do not work in the time line.  Could it be that using the latest D3 the brushes only work in bar chart and not in line chart? The examples you pointed me to (above) are both bar charts.

Please advise.

Thank you.

**Comment by gordonwoodhull** [comment]
Thanks for following up, @ewaldman.

It is only DOM events that have the signature changed, like brush events, mouse events, keyboard, etc.

dc.js chart events are unaffected and still take the arguments documented in [BaseMixin.on](https://dc-js.github.io/dc.js/docs/html/BaseMixin.html#on).

The brush is working in [this line chart](http://dc-js.github.io/dc.js/examples/range-series.html) and it works in the range-series volume chart on the main page. I also tried changing the fluctuation chart to a line chart and that worked. (I just needed to disable some of the bar-specific options.)

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1366709/96494972-21771e80-1215-11eb-96e4-87d43fe764a0.png">

I guess I would need a running example (like a jsfiddle, codepen, observable, or bl.ock - whatever you are comfortable with) in order to see what is going wrong with your code.

**Comment by ewaldman** [comment]
Hi.
We seem to have narrowed down the problem.
Here is the rendlet code - see the bold part

this.timeLineChart.on('renderlet', (chart) => {
chart.select('svg').attr('width', null).attr('height', null).attr('viewBox',
'0 0 ' + TIME_LINE_WIDTH + ' ' + 300)**.attr('preserveAspectRatio', 'xMinYMin')**;
});

When that code is there , the brushes don't filter properly. When I take out that code - and leave the rest - the brushes do work.
We use the rendlet so that the svg resizes when we resize the page.

Any tips? Do we even need that preserveAspectRatio code for our purpose?

Thank you.

**Comment by gordonwoodhull** [comment]
Hmm, I guess you must be doing some kind of automatic resizing when the container resizes. Are you using the built-in [useViewBoxResizing](https://dc-js.github.io/dc.js/docs/html/BaseMixin.html#useViewBoxResizing) or is this something homemade?

Personally I don't like `viewBox` and `preserveAspectRatio` - it's an easy way to get responsive layout but it stretches text and graphics instead of drawing them at the actual resolution. I prefer detecting a resize and doing a redraw with transitions disabled, as shown in the [resizing examples](http://dc-js.github.io/dc.js/resizing/). 

Here is the latest [explainer of this technique](https://stackoverflow.com/questions/63790010/use-css-grid-with-dc-js/63804767#63804767). 

As I said, I don't like `viewBox` resizing so I have never tried d3-brush with it. It would not surprise me if they changed something so that it no longer works with `viewBox` / `preserveAspectRatio`.

**Comment by ewaldman** [comment]
Yesterday we thought that the issue is a 'rendlet' problem. However, today we noticed that even when commenting out rendlet code the brushes don't work in a timeline. (Don't know why I thought it did work yesterday).

The package.json file we are using has this config

"dependencies": {
    "crossfilter2": "^1.5.4",
    "d3": "^6.2.0",
    "dc": "^4.2.0"
  }

You mentioned earlier that the brushes did work in your code.  Can you please check using the above configuration?

Thank you

**Comment by gordonwoodhull** [comment]
Yes, those are the versions used in the demos on the dc.js site. You can check versions in the browser console with 

<img width="217" alt="image" src="https://user-images.githubusercontent.com/1366709/96652809-a6d9fc00-1305-11eb-9502-5e402b274e04.png">

I guess I would need to see a running example to help you further.

**Comment by ewaldman** [comment]
Hi.

Here is the code we are using (obfuscated a bit to protect the innocent....). Perhaps you can tell what we need to do to fix it so that brushes should work.


let data = [
{name: "joe",  timeObserved: 1596819575959}
{ name: "jack",  timeObserved: 1596819575959}
{ name: "jim",  timeObserved: 1596819576000}
{ name: "tom",  timeObserved: 1596819576000}
{ name: "john",  timeObserved: 1596819576000}
{ name: "jill",  timeObserved: 1596819575949}
{ name: "craig",  timeObserved: 1596819580801}
{ name: "norbert",  timeObserved: 1596819575959}
{ name: "donald",  timeObserved: 1596819575949}
];

this.timeLineChart = dc.lineChart('#timeLine');

this.dateDim = this.timeLineChart.dimension((d) => {
        return d3.timeWeek(new Date(d.timeObserved));
      });
	  
this.group = this.dateDim.group().reduceSum((d) => 1);

   let minDate = d3.min(this.group.all(), (kv) => {
        return kv.key;
      });

      let maxDate = d3.max(this.group.all(), (kv) => {
        return kv.key;
      });
	  

let min = 0;
let max = 20;
this.timeLineChart
          .width(470).height(300)
          .dimension(this.dateDim)
          .group(this.group)
          .curve(d3.curveMonotoneX)
          .renderArea(true)
          .mouseZoomable(true)
          .elasticY(true)
          .yAxisPadding(.1)
          .elasticX(true)
          .x(d3.scaleTime().domain([minDate, maxDate]))
          .xUnits(d3.timeWeek.range)
          .yAxis()
          .tickValues(d3.range(min > 0 ? min - 1 : min, max + 1));
        this.timeLineChart.yAxisMin = function() {
          return 0;
        };

**Comment by gordonwoodhull** [comment]
Thanks for the reproducible example!

I should have picked up earlier that you are using a time scale. I had not tested that, and it doesn't look like we currently have an example covering brushing a time-scaled line chart.

I will look into it.

**Comment by gordonwoodhull** [comment]
I did some testing and there is an erroneous zoom event sent after brushing is done, the next time the mouse is moved.

A temporary workaround could be to disable `mouseZoomable`. When mouse zooming is enabled, then any pan or zoom actions also set the filter and thus the brush. (Mouse zooming is strongly tied to range/focus charts.)

So you could say that there is an inherent incompatibility between `mouseZoomable` and brushing - `mouseZoomable` is only intended to be used when the chart is a focus chart paired with a range chart (and the brush is only displayed on the range chart).

That said, it seems strange that we should get a zoom event when we haven't zoomed, so it's still a bug.

**Comment by gordonwoodhull** [comment]
I can reproduce this on the fluctuation chart as well if `mouseZoomable` is enabled. So it's not specific to line charts or time scales.

**Comment by ewaldman** [comment]
We took out mouseEnabled and now the brush does indeed work. 
Is there anyway we can be notified when mouse zooming is fixed?

Thank you so much for all your help.

**Comment by gordonwoodhull** [comment]
Sure, you are subscribed to this ticket, so you will see when we close it.

However, as I pointed out above, `brushOn` is not fully compatible with `mouseZoomable`. Even with d3@5, if you brush and then zoom the chart, the brush will be expanded to cover the whole chart, because `mouseZoomable` is tightly linked to the focus-range feature.

**Comment by ewaldman** [comment]
We have a follow up question. We ripped out our home grown 'renderlet'   code and started using useViewBoxResizing .
The code works, however our jasmine test throws an error now.

Chrome Headless 86.0.4240.111 (Windows 10) myService add to crossfilter FAILED
        TypeError: Cannot read property 'getAttribute' of null
            at Selection.attr (webpack:///node_modules/d3-selection/src/selection/attr.js:50:1 <- index_test.js:44240:16)
            at RowChart.sizeSvg (webpack:///node_modules/dc/dist/dc.js:1751:16 <- index_test.js:55385:37)
            at RowChart.redraw (webpack:///node_modules/dc/dist/dc.js:2003:1 <- index_test.js:55637:16)
            at Object.redrawAll (webpack:///node_modules/dc/dist/dc.js:394:1 <- index_test.js:54028:21)
            at myService.addToCrossfilter (webpack:///myService/js/main/myService.js:2379:10 <- index_test.js:6962:450968)
            at UserContext.<anonymous> (webpack:///myService/js/test/myService.test.js:927:1 <- index_test.js:8670:26)
            at <Jasmine>

The code for sizeSvg is in base-mixin.js.  It seems to be failing in selection in D3 when calling this._svg.attr('viewBox')

sizeSvg () {
        if (this._svg) {
            if (!this._useViewBoxResizing) {
                this._svg
                    .attr('width', this.width())
                    .attr('height', this.height());
            } else if (!this._svg.attr('viewBox')) {
                this._svg
                    .attr('viewBox', `0 0 ${this.width()} ${this.height()}`);
            }
        }
    }

What can we do for this?

**Comment by gordonwoodhull** [comment]
The error indicates that `this._svg` is an empty selection. (Not null, but contains an empty array.)

A couple of conditions could cause this:
- redrawing before rendering
- bad selector passed to the constructor, so `this._root` is empty and therefore `this._svg` is empty as well

**Comment by ewaldman** [comment]
Our test case runs in a "headless chrome". This probably causes it to call redraw before rendering.
How would we work around this problem so that the test doesn't crash/fail?

As an aside, just a suggestion: The code above in sizeSvg  is:

        if (this._svg) {

Why not add another  part to the "if" statement:
 if this._svg is not empty ,  so that the code further on does not crash.

Thank you

**Comment by gordonwoodhull** [comment]
I don’t see why headless chrome would cause this. We use headless chrome for testing, and it still renders everything okay. It’s a fully functional browser; it just isn’t connected to any display.

The error indicates that something in your code is not doing what you expect. So, sure, we could work around the error, but it’s very likely that you have a bug. I don’t see a lot of profit in making sure that operations succeed when the chart is in an inconsistent state.

The most likely issue is the selector being wrong. Please check that `chart.root().size()` is not zero, and then check your selector (and make sure that the corresponding div exists).

Another common error is constructing the chart but never initializing it.

**Comment by ewaldman** [comment]
Regarding the crash when we do testing - see above:

To recap,  dc.renderAll does lots of work, and part of it is a call to sizeSvg. In there the code calls

`if (!this._svg.attr('viewBox'))`

The code in attr.js does the following:

```
export default function(name, value) {
  var fullname = namespace(name);

  if (arguments.length < 2) {
    var node = this.node();
    return fullname.local
        ? node.getAttributeNS(fullname.space, fullname.local)
        : node.getAttribute(fullname);
  }

  return this.each((value == null
      ? (fullname.local ? attrRemoveNS : attrRemove) : (typeof value === "function"
      ? (fullname.local ? attrFunctionNS : attrFunction)
      : (fullname.local ? attrConstantNS : attrConstant)))(fullname, value));
}
```

Following the code we see that the arguments dc passes in is indded less than 2 , -` (svg.attr('viewBox'))` -  so the code
calls var node = this.node();    Turns out that node is null, so the next line of code crashes.

Question:  What can we do about that?  When running the code in real time, the code works well. But by jasmin testing  it crashes as above.  Our code merely calls dc.renderAll. That call causes this entire domino effect. 

Any tips, ideas?

Thank you

**Comment by gordonwoodhull** [comment]
Thanks @ewaldman. 

As I said above, your charts are in an inconsistent state. There is no reason in normal operation why `this._svg` would contain a null selection when `this.sizeSvg` is called.

In particular, your selector is probably wrong when you initialize the chart. Take a look at `generateSvg()`, which will call `resetSvg` in the render case:

https://github.com/dc-js/dc.js/blob/df993a6f7ff56c4f903e80544ac7725dec28363d/src/base/base-mixin.js#L525-L542

See how `this._svg` is generated at the top of the function and `sizeSvg` is called at the bottom, with nothing in between that would invalidate it.

Most likely, `this.root()` is already an invalid selector. Since it is size zero, it fails to create the `svg` tag, and `this._svg` ends up empty as well.

I reproduced the error [in this fiddle](https://jsfiddle.net/gordonwoodhull/1rthqcjL/23/). Note the typo in the selector, `#testf`, when `#test` would work.

My guess is that you have a selector which is not selecting anything, so your test was previously "running in a vacuum" and is now crashing.
